<WelcomeScreen>:
    name: 'welcome'
    MDBoxLayout:
        orientation: 'vertical'
        padding: 30
        spacing: 20

        MDLabel:
            text: "NeuroFit"
            halign: 'center'
            font_style: 'H3'
            theme_text_color: 'Primary'
            size_hint_y: None
            height: 60

        MDLabel:
            text: "Tu entrenador inteligente con IA"
            halign: 'center'
            theme_text_color: 'Secondary'
            size_hint_y: None
            height: self.texture_size[1] + 10

        Widget:
            size_hint_y: 1

        MDRaisedButton:
            text: "Iniciar Proceso"
            md_bg_color: app.theme_cls.primary_color
            size_hint_y: None
            height: 50
            font_size: '18sp'
            pos_hint: {'center_x': 0.5}
            on_release: app.nuevo_registro()   # ← Cambio importante

        Widget:
            size_hint_y: 0.3